version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: breakshop
      MYSQL_USER: host
      MYSQL_PASSWORD: test1234
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
      - "6389:6389"
      - "6399:6399"
      - "6409:6409"
  breakshop:
    image: openjdk:17-jdk-alpine
    container_name: breakshop
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/breakshop?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: host
      SPRING_DATASOURCE_PASSWORD: test1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PASSWORD: 1234
      SPRING_REDIS_SESSION_PORT: 6379
      SPRING_REDIS_CACHE_PORT: 6389
      SPRING_REDIS_CART_PORT: 6399
      SPRING_REDIS_RIDER_PORT: 6409
      FCM_RIDER_EXPIRE_SECOND: 86400
      SPRING_SESSION_STORE_TYPE: redis
#      SPRINGDOCS_PACKAGES-TO-SCAN: com.project.breakshop.controller
#      SPRINGDOCS_SWAGGER-UI_PATH: /index.html
#      SPRINGDOCS_SWAGGER-UI_GROUPS-ORDER: DESC
#      SPRINGDOCS_SWAGGER-UI_OPERATIONSSORTER: method
#      SPRINGDOCS_SWAGGER-UI_DISABLE-SWAGGER-DEFAULT-URL: true
#      SPRINGDOCS_SWAGGER-UI_DISPLAY-REQUEST-DURATION: true
#      SPRINGDOCS_API-DOCS_PATH: /api-docs
#      SPRINGDOCS_SHOW-ACTUATOR: true
#      SPRINGDOC_DEFAULT-CONSUMES-MEDIA-TYPE: application/json
#      SPRINGDOC_DEFAULT-PRODUCES-MEDIA-TYPE: application/json
#      SPRING_MVC_PATHMATCH_MATCHING-STRATEGY: ant_path_matcher
    depends_on:
      - mysql
      - redis